export declare const convertMsToDuration: (ms: number) => string;
export declare const getImageLink: (buffer: Buffer, apiKey: string) => object;
export declare const getImageLinkV2: (buffer: Buffer) => string;
export declare const telegraph: (buffer: Buffer) => string;
export declare const formatSize: (bytes: number) => string;
export declare const isCmd: (m: object, ctx: object) => boolean;
export declare const isAdmin: (ctx: object) => number;
export declare const isAdminOf: (ctx: object) => number;
export declare const download: (object: object, type: string) => Buffer;
export declare const toJID: (number: string) => string;
export declare const toNumber: (jid: string) => string;
export declare const logg: (o: Array) => undefined;
export declare const isGroup: (jid: string) => boolean;
export declare const Msg: (flx: object) => object;
export declare const Sender: (flx: object) => object;
export declare const serialize: (f: object, m: object) => object;
export declare const getBuffer: (url: string, options: object) => Buffer;
//# sourceMappingURL=Simple.d.ts.map